
services:
  mc:
    extends:
      file: ../mc-commons/mc-common.yml
      service: mc
    env_file: mc-variables.env

  restore-backup:
    extends:
      file: ../mc-commons/mc-common.yml
      service: restore-backup

  mc-backup:
    extends:
      file: ../mc-commons/mc-common.yml
      service: mc-backup

networks:
  minecraft-net:
  splunknet:
    name: splunk_splunknet
    external: true

volumes:
  data: {}
  
