
services:
  mc:
    extends:
      file: ../mc-commons/mc-common.yml
      service: mc
    env_file: mc-variables.env

  mc-backup:
    extends:
      file: ../mc-commons/mc-common.yml
      service: mc-backup

networks:
  minecraft-net:
  minio-net:
    external: true

volumes:
  data: {}
  restore: {}
